FROM alpine:latest

ENV PYTHONUNBUFFERED=1

RUN apk add --update --no-cache python3 && ln -sf python3 /usr/bin/python \
    && python3 -m ensurepip 						  \
    && pip3 install --no-cache --upgrade pip setuptools

RUN pip3 install --no-cache flask-restful

WORKDIR /usr/src/webapp

COPY ./webapp /usr/src/webapp

